services:
  kube_news:
    image: delgaka/kube-news:${KUBE_NEWS_TAG:-latest} # define imagem padrão latest quando não há tag definida na variável.
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: kube_news
    ports:
      - "8080:8080"
    networks:
      - kube_news_net
    depends_on:
      - postgre
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgre
